[workspace]

members = [
    "adder",
    "add-one",
]

[raze]
workspace_path = "//remote/cargo_workspace"
target = "x86_64-unknown-linux-gnu"
gen_workspace_prefix = "cargo_workspace"
genmode = "Remote"
output_buildfile_suffix = "BUILD.bazel"
